from modules.commandadd import command_add
from modules.commandretrieve import command_retrieve
from modules.commandremove import command_remove
from modules.ping import ping
from modules.reverse import reverse
from modules.spongebob import spongebob
from modules.timer import timer
from modules.avatar import avatar
from modules.math import math_func
from modules.joke import joke
from modules.weather import weather
from modules.rps import rps
from modules.youtube import youtube
from modules.slap import slap
from modules.stab import stab
from modules.lmgtfy import lmgtfy
from modules.google import google
from modules.geolocation import geolocation
from modules.translate import translate
from modules.gettime import time_new
from modules.lennyface import lennyface
from modules.getpointsamount import points
from modules.getxpamount import user_xp
from modules.wikipedia import wikipedia
from modules.toplist import top
from modules.daily import daily
from modules.catfact import catfact
from modules.catpicture import random_cat
from modules.dogfact import dogfact
from modules.dogpicture import random_dog
from modules.pun import pun
from modules.gender import gender
from modules.trump import trump
from modules.numberfact import number_fact
from modules.ip import ip
from modules.bitcoin import bitcoin
from modules.strawpoll import strawpoll
from modules.eightball import eight_ball
from modules.getnicknames import get_nicknames
from modules.choose import choose
from modules.dice import dice
from modules.online import online
from modules.meme import meme
from modules.roulette import roulette
from modules.guess import guess
from modules.duel import duel
from modules.joinedtoserver import joined
from modules.osustats import osu_player
from modules.urban import urban
from modules.help import commands_help
from modules.roll import roll
from modules.transferpoints import transfer_points
from modules.shop import shop
from modules.casino import casino
from modules.tokens import user_tokens
from modules.playing import set_bot_playing
from modules.roles import roles
from modules.gamble import gamble
from modules.test import test
from modules.yomama import yo_mama
from modules.dad import dad_joke
from modules.chucknorris import chuck_norris
from modules.pot import tax_pot
from modules.join import raffle_lotto
from modules.slotmachine import slot_machine
from modules.tuplat import tuplat
from modules.purge import purge
from modules.setavatar import set_avatar
from modules.black_jack import black_jack
from modules.fishing import fishing
from modules.ao_ruoka import ao_ruoka
from modules.chronogg import chronogg
from modules.server_stats import server_stats
from modules.bank import bank
from modules.userinfo import userinfo
